version: "2"

volumes:
  seedlara8-mysql-data:
    driver: local

  seedlara8-redis-data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: seedlara8-mysql
    volumes:
      - seedlara8-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=seedlara8
      - MYSQL_DATABASE=seedlara8
      - MYSQL_USER=seedlara8
      - MYSQL_PASSWORD=seedlara8

  cache:
    image: redis:4.0
    container_name: seedlara8-redis
    command: --appendonly yes
    volumes:
      - seedlara8-redis-data:/data
    ports:
      - "6380:6379"

  app:
    image: ambientum/php:8.0-nginx
    container_name: seedlara8-app
    volumes:
      - .:/var/www/app
    ports:
      - "8081:8080"
    environment:
      XDEBUG_ENABLED: "true"
    links:
      - mysql
      - cache
